# You can sponsor

github: [h9zdev] # GitHub Sponsors-enabled username for https://github.com/haybnzz/HadesConnect
patreon: https://www.patreon.com/c/Fluromide
liberapay: https://liberapay.com/Floraminde/
custom: https://haybnz.web.app/tip.html # Custom Monero donation link and address
